// Copyright(c) 2013 Bluebird Inc. All rights reserved.
package de.dimedis.mobileentry.bbapi

object BBAPI {
    //+ RESULT
    const val BBAPI_SUCCESS = 0
    const val BBAPI_FAILED = -1
    const val BBAPI_NOT_SUPPORTED = -2
    const val BBAPI_ERROR_CHECKSUM = -3
    const val BBAPI_ERROR_NO_RESPONSE = -4
    const val BBAPI_BATTERY_LOW = -5

    //MSR
    const val BBAPI_ERROR_MSR_TIMEOUT = -6
    const val BBAPI_ERROR_MSR_BAD_DATA = -7
    const val BBAPI_ERROR_MSR_NO_DATA = -8
    const val BBAPI_ERROR_MSR_BUSY = -9
    const val BBAPI_ERROR_MSR_COPY_FAULT = -10

    //Barcode
    const val BBAPI_ERROR_BARCODE_DECODING_TIMEOUT = -6
    const val BBAPI_ERROR_BARCODE_USE_TIMEOUT = -7
    const val BBAPI_ERROR_BARCODE_ALREADY_OPENED = -8
    const val BBAPI_ERROR_BARCODE_CAMERA_USED = -9

    //- RESULT
    //+ DEVICE KEY CODE
    const val KEYCODE_SCAN_PRESS = 0
    const val KEYCODE_SCAN_RELEASE = 1
    const val KEYCODE_PTT_PRESS = 2
    const val KEYCODE_PTT_RELEASE = 3
    const val KEYCODE_VOLUME_PRESS = 4
    const val KEYCODE_VOLUME_RELEASE = 5

    //- DEVICE KEY CODE
    //+ MSR MODE
    const val MSR_MODE_READING_TIMEOUT = 0

    //- MSR MODE
    //+ BARCODE MODE
    const val BARCODE_MODE_PREFIX = 500
    const val BARCODE_MODE_SUFFIX = BARCODE_MODE_PREFIX + 1
    const val BARCODE_MODE_SOUND = BARCODE_MODE_PREFIX + 2
    const val BARCODE_MODE_TRIGGER = BARCODE_MODE_PREFIX + 3
    const val BARCODE_MODE_AIMER = BARCODE_MODE_PREFIX + 4
    const val BARCODE_MODE_ILLUMINATION = BARCODE_MODE_PREFIX + 5
    const val BARCODE_MODE_DECODE_TIMEOUT = BARCODE_MODE_PREFIX + 6
    const val BARCODE_MODE_SAME_SYMBOL_TIMEOUT = BARCODE_MODE_PREFIX + 7
    const val BARCODE_MODE_POSTAMBLE = BARCODE_MODE_PREFIX + 43
    const val BARCODE_MODE_SUBAMBLE = BARCODE_MODE_PREFIX + 44
    const val BARCODE_MODE_DATA_WEDGE = BARCODE_MODE_PREFIX + 45
    const val BARCODE_MODE_USE_TIMEOUT = BARCODE_MODE_PREFIX + 46
    const val BARCODE_MODE_DATA_WEDGE_TYPE = BARCODE_MODE_PREFIX + 47

    //- BARCODE MODE
    //+ BARCODE SYMBOLOGY
    const val SYMBOLOGY_UPC_A = 1
    const val SYMBOLOGY_UPC_E = 2
    const val SYMBOLOGY_UPC_E1 = 3
    const val SYMBOLOGY_EAN8 = 4
    const val SYMBOLOGY_EAN13 = 5
    const val SYMBOLOGY_BOOKLAND = 6
    const val SYMBOLOGY_SUPPLEMENTAL_CODE = 7
    const val SYMBOLOGY_CODE39 = 8
    const val SYMBOLOGY_CODE93 = 9
    const val SYMBOLOGY_CODE128 = 10
    const val SYMBOLOGY_INTERLEAVED2OF5 = 11
    const val SYMBOLOGY_CODABAR = 12
    const val SYMBOLOGY_CODE11 = 13
    const val SYMBOLOGY_MSI = 14
    const val SYMBOLOGY_GS1 = 15
    const val SYMBOLOGY_PDF417 = 16
    const val SYMBOLOGY_ISBT128 = 17
    const val SYMBOLOGY_COMPOSITE_CC_C = 18
    const val SYMBOLOGY_MATRIX2OF5 = 19
    const val SYMBOLOGY_DATAMATRIX = 20
    const val SYMBOLOGY_MAXICODE = 21
    const val SYMBOLOGY_AZTECCODE = 22
    const val SYMBOLOGY_MICROPDF = 23
    const val SYMBOLOGY_QRCODE = 24
    const val SYMBOLOGY_TRIOPTIC_CODE = 25
    const val SYMBOLOGY_DISCRETE2OF5 = 26
    const val SYMBOLOGY_USPS4CB = 27
    const val SYMBOLOGY_AUSTRALIA_POST = 28
    const val SYMBOLOGY_UK_POST = 29
    const val SYMBOLOGY_CHINESE_POST = 30
    const val SYMBOLOGY_JAPANESE_POST = 31
    const val SYMBOLOGY_NETHERLANDS_POST = 32
    const val SYMBOLOGY_KOREAN_POST = 33
    const val SYMBOLOGY_US_POSTNET = 34
    const val SYMBOLOGY_US_PLANET = 35
    const val SYMBOLOGY_UPC_A_PREAMBLE = 36
    const val SYMBOLOGY_UPC_A_TRANSMIT_CHECK_DIGIT = 37
    const val SYMBOLOGY_UPC_E_PREAMBLE = 38
    const val SYMBOLOGY_UPC_E_TRANSMIT_CHECK_DIGIT = 39
    const val SYMBOLOGY_UPC_E1_PREAMBLE = 40
    const val SYMBOLOGY_UPC_E1_TRANSMIT_CHECK_DIGIT = 41
    const val SYMBOLOGY_EAN8_EXTEND = 42
    const val SYMBOLOGY_EAN_TRANSMIT_ISSN = 43
    const val SYMBOLOGY_BOOKLAND_ISBN = 44
    const val SYMBOLOGY_SUPPLEMENTAL_REDUNDANCY = 45
    const val SYMBOLOGY_SUPPLEMENTAL_AIM_ID = 46
    const val SYMBOLOGY_CODE39_LENGTH_MIN = 47
    const val SYMBOLOGY_CODE39_LENGTH_MAX = 48
    const val SYMBOLOGY_CODE39_CHECK_DIGIT = 49
    const val SYMBOLOGY_CODE39_TRANSMIT_CHECK_DIGIT = 50
    const val SYMBOLOGY_CODE39_FULL_ASCII = 51
    const val SYMBOLOGY_CODE93_LENGTH_MIN = 52
    const val SYMBOLOGY_CODE93_LENGTH_MAX = 53
    const val SYMBOLOGY_CODE128_LENGTH_MIN = 54
    const val SYMBOLOGY_CODE128_LENGTH_MAX = 55
    const val SYMBOLOGY_CODE128_EMULATION = 56
    const val SYMBOLOGY_INTERLEAVED2OF5_LENGTH_MIN = 57
    const val SYMBOLOGY_INTERLEAVED2OF5_LENGTH_MAX = 58
    const val SYMBOLOGY_INTERLEAVED2OF5_CHECK_DIGIT = 59
    const val SYMBOLOGY_INTERLEAVED2OF5_TRANSMIT_CHECK_DIGIT = 60
    const val SYMBOLOGY_CODABAR_LENGTH_MIN = 61
    const val SYMBOLOGY_CODABAR_LENGTH_MAX = 62
    const val SYMBOLOGY_CODABAR_CLSI_EDITING = 63
    const val SYMBOLOGY_CODABAR_NOTIS_EDITING = 64
    const val SYMBOLOGY_CODE11_LENGTH_MIN = 65
    const val SYMBOLOGY_CODE11_LENGTH_MAX = 66
    const val SYMBOLOGY_CODE11_CHECK_DIGIT = 67
    const val SYMBOLOGY_CODE11_TRANSMIT_CHECK_DIGIT = 68
    const val SYMBOLOGY_MSI_LENGTH_MIN = 69
    const val SYMBOLOGY_MSI_LENGTH_MAX = 70
    const val SYMBOLOGY_MSI_CHECK_DIGIT = 71
    const val SYMBOLOGY_MSI_TRANSMIT_CHECK_DIGIT = 72
    const val SYMBOLOGY_MSI_CHECK_DIGIT_ALGORITHM = 73
    const val SYMBOLOGY_GS1_LIMITED = 74
    const val SYMBOLOGY_GS1_LIMITED_SECURITY_LEVEL = 75
    const val SYMBOLOGY_ISBT128_CONCATENATION = 76
    const val SYMBOLOGY_ISBT128_CHECK_TABLE = 77
    const val SYMBOLOGY_ISBT128_CONCATENATION_REDUNDANCY = 78
    const val SYMBOLOGY_MATRIX2OF5_LENGTH_MIN = 79
    const val SYMBOLOGY_MATRIX2OF5_LENGTH_MAX = 80
    const val SYMBOLOGY_MATRIX2OF5_SUPPLEMENTAL_REDUNDANCY = 81
    const val SYMBOLOGY_MATRIX2OF5_CHECK_DIGIT = 82
    const val SYMBOLOGY_MATRIX2OF5_TRANSMIT_CHECK_DIGIT = 83
    const val SYMBOLOGY_COMPOSITE_CC_AB = 84
    const val SYMBOLOGY_COMPOSITE_TLC_39 = 85
    const val SYMBOLOGY_COMPOSITE_UPC = 86
    const val SYMBOLOGY_DATAMATRIX_INVERSE = 87
    const val SYMBOLOGY_DATAMATRIX_ONLY = 88
    const val SYMBOLOGY_DISCRETE2OF5_LENGTH_MIN = 89
    const val SYMBOLOGY_DISCRETE2OF5_LENGTH_MAX = 90
    const val SYMBOLOGY_US_TRANSMIT_CHECK_DIGIT = 91
    const val SYMBOLOGY_QRCODE_INVERSE = 92
    const val SYMBOLOGY_SPECIFIC_SECURITY = 93
    const val SYMBOLOGY_SPECIFIC_INTERCHARACTER = 94
    const val SYMBOLOGY_COUPON_REPORT = 95
    const val SYMBOLOGY_CONVERT_UPCE_TO_A = 96
    const val SYMBOLOGY_CONVERT_UPCE1_TO_A = 97
    const val SYMBOLOGY_CONVERT_CODE39_TO_32 = 98
    const val SYMBOLOGY_CONVERT_I2OF5_TO_EAN13 = 99
    const val SYMBOLOGY_CONVERT_GS1_TO_UPCEAN = 100
    const val SYMBOLOGY_GS1_DATABAR_EXPANDED = 101
    const val SYMBOLOGY_GS1_128_EMULATION_FOR_UCC_COMPOSITE_CODE = 102
    const val SYMBOLOGY_INVERSE_1D = 103
    const val SYMBOLOGY_UPU_FICS_POSTAL = 104
    const val SYMBOLOGY_UPC_COMPOSITE_MODE = 105
    const val SYMBOLOGY_AZTEC_INVERSE = 106
    const val SYMBOLOGY_SPECIFIC_REDUNDANCY_LEVEL = 107
    const val SYMBOLOGY_AUSTRALIA_POST_FORMAT = 108
    const val SYMBOLOGY_TRANSMIT_UK_POST_CHECK_DIGIT = 109
    const val SYMBOLOGY_CODE32_PREFIX = 110
    const val SYMBOLOGY_USER_SUPPLEMENTAL_1 = 111
    const val SYMBOLOGY_USER_SUPPLEMENTAL_2 = 112
    const val SYMBOLOGY_MICROQR = 113
    const val SYMBOLOGY_HANXIN = 134
    const val SYMBOLOGY_HANXIN_INVERSE = 135 //- BARCODE SYMBOLOGY
}