package de.dimedis.mobileentry.util;

public enum SoundType {
    TICKET_SCAN_STATUS_OK,
    TICKET_SCAN_STATUS_OK_REDUCED_TICKET,
    TICKET_SCAN_STATUS_NOT_OK,
    CODE_SCAN_OK_OR_MANUAL_ACCEPTED,
    CODE_SCAN_REFUSED_OR_ALREADY_PROCESSING,
    GENERAL_ERROR
}
